apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: task-pv-claim
spec: 
  accessModes: 
    - ReadWriteOnce 
  volumeMode: Filesystem 
  resources: 
    requests: 
      storage: 10G 
  storageClassName: 
