apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-replicaset-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: nginx-replicaset
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
